Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [1]:
import numpy as np

n = int(input('Введите число N: '))
a_list = [i for i in range(0,n)]
a_list.reverse()

arr = np.array(a_list)
mat = np.diag(arr)
print(mat)
print(sum(mat.diagonal()))


Введите число N: 5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
10
